theme: jekyll-theme-cayman
title: LLM-Driven Sentiment-Momentum Trading Strategy
description: "Exploring the use of Large Language Models in developing a trading strategy that outperforms the S&P 500."
author:
  name: Ju Hyung Kang
  affiliation: Mathematics in Finance, Courant Institute of Mathematical Sciences, NYU
navbar:
  - title: Home
    url: /
  - title: Problem Statement
    url: /problem-statement/
  - title: Summary
    url: /summary/
  - title: Methodology
    url: /methodology/
  - title: Data Insights
    url: /data-insights/
  - title: Findings
    url: /findings/
  - title: Conclusion
    url: /conclusion/
  - title: Appendix
    url: /appendix/
